# Generated by Django 3.1.2 on 2020-12-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Board_line_number',
            new_name='board_line_number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Facebook',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Linkedin',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Twitter',
            new_name='twitter',
        ),
    ]
