# Generated by Django 3.1.2 on 2020-12-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20201224_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='addressssssss',
        ),
    ]
