# Generated by Django 3.1.2 on 2020-12-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20201224_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='addressssssss',
            new_name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='stream',
            field=models.CharField(choices=[('n', 'NA'), ('s1', 'STREAM_1'), ('s2', 'STREAM_2'), ('s3', 'STREAM_3')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='school',
            field=models.CharField(choices=[('n', 'NA'), ('s1', 'School_1'), ('s2', 'School_2'), ('s3', 'School_3')], default='NA', max_length=20),
        ),
    ]
