# Generated by Django 3.1.2 on 2020-12-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20201224_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='stream',
        ),
    ]
