# Generated by Django 3.1.2 on 2020-12-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_remove_contact_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='stream',
            field=models.CharField(choices=[('n', 'NA'), ('s1', 'STREAM_1'), ('s2', 'STREAM_2'), ('s3', 'STREAM_3')], default='NA', max_length=20),
        ),
    ]
