# Generated by Django 3.1.2 on 2020-12-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20201225_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='designation',
            field=models.CharField(choices=[('NA', 'NA'), ('HR', 'HR'), ('Finance', 'Finance'), ('Administration', 'Administration'), ('Accounts', 'Accounts'), ('IT', 'IT'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Technical', 'Technical'), ('Purchase', 'Purchase')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='referred_by',
            field=models.CharField(choices=[('NA', 'NA'), ('Mr A.', 'Mr A.'), ('Mr B', 'Mr B'), ('Mr C', 'Mr C')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='salutation',
            field=models.CharField(choices=[('NA', 'NA'), ('Colonel', 'Colonel'), ('Mr.', 'Mr.'), ('Mrs', 'Mrs.'), ('Dr', 'Dr')], default='NA', max_length=20),
        ),
    ]
