# Generated by Django 3.1.2 on 2020-12-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20201225_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Of_details',
            field=models.CharField(choices=[('NA', 'NA'), ('Head Office', 'Head Office'), ('Factory / Plant', 'Factory / Plant'), ('Branch Office', 'Branch Office'), ('Project Site', 'Project Site'), ('Regional Office', 'Regional Office'), ('Registered Office', 'Registered Office'), ('Zonal Office', 'Zonal Office')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='month',
            field=models.CharField(choices=[('month', 'month'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='school',
            field=models.CharField(choices=[('NA', 'NA'), ('School 1', 'School 1'), ('School 2', 'School 2'), ('School 3', 'School 3')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='stream',
            field=models.CharField(choices=[('NA', 'NA'), ('Stream1.1', 'Stream1.1'), ('Stream 1.2', 'Stream 1.2'), ('Stream 1.3', 'Stream 1.3')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='year',
            field=models.CharField(choices=[('year', 'year'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], default='NA', max_length=20),
        ),
    ]
