# Generated by Django 3.1.2 on 2020-12-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20201227_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='institution',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
