# Generated by Django 3.1.2 on 2020-12-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_contact_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email1',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
