# Generated by Django 3.1.2 on 2020-12-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_auto_20201229_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='board_line_number1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='mob_no1',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
